package org.jug.nicaragua.picoweb.modelo;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import com.vaadin.annotations.AutoGenerated;

@Entity
@Table(name = "Departamentos")
public class Departamento implements Serializable {

  private static final long serialVersionUID = -4538016228594995239L;
  @Id @AutoGenerated @GeneratedValue(strategy=GenerationType.IDENTITY)
  private Integer id;  
  private String Departamento;
  @Column(length=255)
  private String descripcion ="";
  private int idsuperior = 0;
  private int idresponsable=0;
  private int creadopor=0;
  private Date fechaCreacion;
  
  
  public Departamento() {
    
  }
  
  //

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public String getDepartamento() {
    return Departamento;
  }

  public void setDepartamento(String departamento) {
    Departamento = departamento;
  }

  public String getDescripcion() {
    return descripcion;
  }

  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }

  public int getIdsuperior() {
    return idsuperior;
  }

  public void setIdsuperior(int idsuperior) {
    this.idsuperior = idsuperior;
  }

  public int getIdresponsable() {
    return idresponsable;
  }

  public void setIdresponsable(int idresponsable) {
    this.idresponsable = idresponsable;
  }

  public int getCreadopor() {
    return creadopor;
  }

  public void setCreadopor(int creadopor) {
    this.creadopor = creadopor;
  }

  public Date getFechaCreacion() {
    return fechaCreacion;
  }

  public void setFechaCreacion(Date fechaCreacion) {
    this.fechaCreacion = fechaCreacion;
  }
   

}
