package org.jug.nicaragua.picoweb.modelo;


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import com.vaadin.annotations.AutoGenerated;

@Entity
@Table(name = "Empleados")
public class Empleado  implements Serializable {

  private static final long serialVersionUID = 3586681125212196431L;
  //
  @Id @AutoGenerated @GeneratedValue(strategy=GenerationType.IDENTITY)
  private Integer id;
  //
  private Date fechaContracion;
  private Date fechaRetiro;
  @OneToOne
  @JoinColumn(name = "iddepartamento")
  private Departamento departmento;
  private Integer idCargo;
  //seguimiento
  private int creadopor=0;
  private Date fechaCreacion;

}
