package org.jug.nicaragua.picoweb.modelo;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import com.vaadin.annotations.AutoGenerated;

@Entity
public class EvalCapacitacion implements Serializable {

  private static final long serialVersionUID = -4538016228594995239L;
  //
  @Id @AutoGenerated @GeneratedValue(strategy=GenerationType.IDENTITY)
  private Integer id;  
  private Integer codCapacitacion;
  @OneToOne
  @JoinColumn(name = "idevaluado")
  private Persona evaluado;
  private Date fecha;
  @OneToOne
  @JoinColumn(name = "idevaluador")
  private Persona evaluador;
  private String periodo;
  private Integer antiguedad; // en meses.
  @Column(length=300)
  private String fortalezas;
  @Column(length=300)
  private String debilidades;
  @Column(length=300)
  private String observaciondel;
  @Column(length=300)
  private String observaciones;
  @Column(length=300)
  private String conclusiones;
  //estado
  private Integer estatus;
  //seguimiento
  private int creadopor=0;
  private Date fechaCreacion;
  
  
  public EvalCapacitacion() {
  }


  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public Integer getCodCapacitacion() {
    return codCapacitacion;
  }


  public void setCodCapacitacion(Integer codCapacitacion) {
    this.codCapacitacion = codCapacitacion;
  }


  public Persona getEvaluado() {
    return evaluado;
  }


  public void setEvaluado(Persona evaluado) {
    this.evaluado = evaluado;
  }


  public Date getFecha() {
    return fecha;
  }


  public void setFecha(Date fecha) {
    this.fecha = fecha;
  }


  public Persona getEvaluador() {
    return evaluador;
  }


  public void setEvaluador(Persona evaluador) {
    this.evaluador = evaluador;
  }


  public String getPeriodo() {
    return periodo;
  }


  public void setPeriodo(String periodo) {
    this.periodo = periodo;
  }


  public Integer getAntiguedad() {
    return antiguedad;
  }


  public void setAntiguedad(Integer antiguedad) {
    this.antiguedad = antiguedad;
  }


  public String getFortalezas() {
    return fortalezas;
  }


  public void setFortalezas(String fortalezas) {
    this.fortalezas = fortalezas;
  }


  public String getDebilidades() {
    return debilidades;
  }


  public void setDebilidades(String debilidades) {
    this.debilidades = debilidades;
  }


  public String getObservaciondel() {
    return observaciondel;
  }


  public void setObservaciondel(String observaciondel) {
    this.observaciondel = observaciondel;
  }


  public String getObservaciones() {
    return observaciones;
  }


  public void setObservaciones(String observaciones) {
    this.observaciones = observaciones;
  }


  public String getConclusiones() {
    return conclusiones;
  }


  public void setConclusiones(String conclusiones) {
    this.conclusiones = conclusiones;
  }


  public Integer getEstatus() {
    return estatus;
  }


  public void setEstatus(Integer estatus) {
    this.estatus = estatus;
  }


  public int getCreadopor() {
    return creadopor;
  }


  public void setCreadopor(int creadopor) {
    this.creadopor = creadopor;
  }


  public Date getFechaCreacion() {
    return fechaCreacion;
  }


  public void setFechaCreacion(Date fechaCreacion) {
    this.fechaCreacion = fechaCreacion;
  }
  
 
}
