package org.jug.nicaragua.picoweb.modelo;


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import com.vaadin.annotations.AutoGenerated;

@Entity
@Table(name = "NombreTbla")
public class Plantilla implements Serializable{

  //
  @Id @AutoGenerated @GeneratedValue(strategy=GenerationType.IDENTITY)
  private Integer id;
  //
  
  //seguimiento
  private int creadopor=0;
  private Date fechaCreacion;

}
