package org.jug.nicaragua.picoweb.modelo;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import com.vaadin.annotations.AutoGenerated;

@Entity
@Table(name = "Procesos")
public class Proceso implements Serializable {

  private static final long serialVersionUID = -4538016228594995239L;
  @Id @AutoGenerated @GeneratedValue(strategy=GenerationType.IDENTITY)
  private Integer id;  
  private String proceso;
  @Column(length=255)
  private String descripcion ="";
  private int idsupserior = 0;
  private int idresponsable=0;
  private int creadopor=0;
  private Date fechaCreacion;
  
  
  public Proceso() {
    
  }
  
  public Proceso(String p) {
    setProceso( p);
  }
  //
 
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }
  public String getProceso() {
    return proceso;
  }
  public void setProceso(String proceso) {
    this.proceso = proceso;
  }
  public String getDescripcion() {
    return descripcion;
  }
  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }
  public int getCreadopor() {
    return creadopor;
  }
  public void setCreadopor(int creadopor) {
    this.creadopor = creadopor;
  }
  public Date getFechaCreacion() {
    return fechaCreacion;
  }
  public void setFechaCreacion(Date fechaCreacion) {
    this.fechaCreacion = fechaCreacion;
  }

  @Override
  public String toString() {
    return  proceso ;
  }

  public int getIdsupserior() {
    return idsupserior;
  }

  public void setIdsupserior(int idsupserior) {
    this.idsupserior = idsupserior;
  }

  public int getIdresponsable() {
    return idresponsable;
  }

  public void setIdresponsable(int idresponsable) {
    this.idresponsable = idresponsable;
  } 
  

}
